#pragma once

#include "froaring_api/and.h"
#include "froaring_api/and_inplace.h"
#include "froaring_api/array_container.h"
#include "froaring_api/bitmap_container.h"
#include "froaring_api/diff.h"
#include "froaring_api/diff_inplace.h"
#include "froaring_api/equal.h"
#include "froaring_api/mix_ops.h"
#include "froaring_api/or.h"
#include "froaring_api/or_inplace.h"
#include "froaring_api/prelude.h"
#include "froaring_api/rle_container.h"
#include "froaring_api/utils.h"